- name: Install nodejs PPA
  shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

- name: Install packages
  sudo: true
  apt: pkg={{ item }} state=installed
  with_items:
    - nodejs
    - build-essential
    - python-dev
    - libssl-dev
    - libffi-dev
    - imagemagick

- name: Copy files
  copy: src={{item.file}} dest={{item.path}}
  with_items:
    - {file: 'install_lektor.py', path: '~/install_lektor.py'}
    - {file: 'ssh_config', path: '~/.ssh/config'}
    - {file: '/vagrant/deploy/id_rsa', path: '~/.ssh/id_rsa'}

- name: Set permissions
  file: path=~/.ssh/id_rsa mode=0600

- name: Install Lektor
  sudo: true
  command: python /home/vagrant/install_lektor.py